--
-- Extras
--
plug("plugins.extras.gitlinker")
plug("plugins.extras.indent-blankline")
plug("plugins.extras.lastplace")
plug("plugins.extras.noice")
plug("plugins.extras.persistence")
plug("plugins.extras.todo-comments")
plug("plugins.extras.twilight")
plug("plugins.extras.wakatime")
plug("plugins.extras.which-key")
plug("plugins.extras.spectre")
plug("plugins.extras.obsidian")
plug("plugins.extras.mini")
plug("plugins.extras.tpope")
plug("plugins.extras.cppman")
plug("plugins.extras.tmux-navigator")
-- plug("plugins.extras.suave")
-- plug("plugins.extras.plantuml")
-- plug("plugins.extras.alpha")
-- plug("plugins.extras.neoscroll")
