#!/bin/bash

file=/tmp/$(date "+%Y%m%d-%H%M%S")_screenshot.png
grim -g "$(slurp)" - | satty --filename - --fullscreen --save-after-copy --output-filename $file &&
	yad --title="Upload?" --text="Upload OK?" --image="dialog-question" --default-cancel &&
	curl -F"file=@$file" https://0x0.st | xargs xdg-open
