#!/bin/bash

# runs a command with an optional delay
function run {
  delay=$1
  shift # remove delay from args
  if [ -z "$delay" ]; then
    delay=0
  fi
  (sleep "$delay"; exec "$@") &
}

run 0 gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
run 0 dunst
run 0 waybar.sh

# Applets
run 0 blueman-applet
run 0 nm-applet
run 0 firewall-applet
run 0 easyeffects --gapplication-service

# Random wallpaper
run 0 randwall

# Clipboard manager
run 0 wl-paste --type text --watch cliphist store
run 0 wl-paste --type image --watch cliphist store
run 0 cliphist wipe

run 0 foot --server

# Low Priority
run 1 footclient -a dropdown
run 1 vorta
run 1 slack
run 1 GTK_THEME=Mist evolution
run 1 /opt/firefox/firefox-bin
