#!/bin/env bash

# if no	argument is given, use the current directory
if [ $# -eq 0 ]; then
	DIR="."
	file_name=$DIR
else
	# if the is a file, use the directory of the file
	if [ -f $1 ]; then
		file_name=$1
		DIR=$(dirname $1)
	else
		DIR=$1
		file_name=$DIR
	fi
fi

directory_name=$(basename $DIR)
title="presenterm ~ $directory_name"
command="presenterm $file_name"

swaymsg "[app_id=\"${title}\"]" focus >/dev/null 2>&1

if [ $? -ne 0 ]; then
	exec wezterm-gui start --cwd "${DIR}" --class "$title" $command
	sleep 0.2
fi

swaymsg "[app_id=\"${title}\"]" focus >/dev/null 2>&1
