require("mzunino.launch")

require("mzunino.remap")
require("mzunino.options")
require("mzunino.autocmd")

spec("plugins.bfq")
spec("plugins.cloak")
spec("plugins.cmp")
spec("plugins.colorizer")
spec("plugins.colors")
spec("plugins.comment")
spec("plugins.conform")
spec("plugins.copilot")
spec("plugins.dressing")
spec("plugins.fold")
spec("plugins.gitsigns")
spec("plugins.harpoon")
spec("plugins.latex")
spec("plugins.lsp")
spec("plugins.lualine")
spec("plugins.markdown")
spec("plugins.mason")
spec("plugins.neogit")
spec("plugins.navic")
spec("plugins.nvim-lint")
spec("plugins.oil")
spec("plugins.schema-store")
spec("plugins.snippets")
spec("plugins.telescope")
spec("plugins.treesitter")
spec("plugins.trouble")
spec("plugins.undotree")

--
-- Extras
--
spec("plugins.extras.gitlinker")
spec("plugins.extras.indent-blankline")
spec("plugins.extras.lastplace")
spec("plugins.extras.noice")
spec("plugins.extras.persistence")
spec("plugins.extras.todo-comments")
spec("plugins.extras.twilight")
spec("plugins.extras.wakatime")
spec("plugins.extras.which-key")
spec("plugins.extras.spectre")
spec("plugins.extras.obsidian")
-- spec("plugins.extras.suave")
-- spec("plugins.extras.plantuml")
-- spec("plugins.extras.alpha")
-- spec("plugins.extras.neoscroll")

require("mzunino.lazy")
